version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./output:/app/output
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - tensortrade

  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
      - ./output:/app/output
      - ./logs:/app/logs
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - tensortrade

  wss:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8765:8765"
    command: ["python", "-m", "src.simulation.server"]
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - tensortrade

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tensortrade

networks:
  tensortrade:
    driver: bridge

volumes:
  redis_data: